#+TITLE: My server scripts

These are a bunch of scripts for my VPS server. They might only run on BSD servers.

* Dependecies
- *BSD*-type operating system
- ~perl~
- ~dash~ shell
- ~ssh~
- ~git~
- ~stagit~

* Functions
The source tree is the following:

#+BEGIN_SRC shell
└── src
    ├── gitjoe
    │   ├── addsshkey.pl
    │   ├── adduser.pl
    │   ├── chdesc.pl
    │   ├── chowner.pl
    │   ├── newrepo.pl
    │   ├── rmrepo.pl
    │   └── rmuser.pl
    ├── other
    │   └── git-ro-daemon.pl
    ├── update
    │   ├── gitjoe.pl
    │   └── vps.pl
    └── vps-do.pl
#+END_SRC

- ~gitjoe/~ scripts are meant to be run on the server directly. They are tools to add GitJoe users, repos, change descritpion, etc.
- ~update/~ scripts are run via cron jobs. They update the GitJoe repositories front-end website via ~stagit~ and pull ~master~ branches of the websites via ~git~.
- ~other/~ script is just a single line the start the ~git daemon~ to serve public repositories.
- The ~vps-do.pl~ script allows you to execute one of the distant scripts from your home terminal, opening and closing the ~ssh~ session for you. You still need the ~dash~ shell as a dependency on your home terminal.
